# -*- mode: ruby -*-
# vi: set ft=ruby :

# Check required plugins
REQUIRED_PLUGINS = %w(vagrant-junos_cli vagrant-junos vagrant-host-shell)
exit unless REQUIRED_PLUGINS.all? do |plugin|
  Vagrant.has_plugin?(plugin) || (
    puts "The #{plugin} plugin is required. Please install it with:"
    puts "$ vagrant plugin install #{plugin}"
    false
  )
end

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

# This section is where the topology is defined. Vagrant will define what
# the topology will look like. The file give instructions to VirtualBox
# on how all the vSRXs are connected. This is how the physical environment 
# will be set up. Additionally resources are allocated to each VM 

# Jump Box 1
    config.vm.define "hosts1" do |hosts1|
        hosts1.vm.box = "ubuntu/xenial64"
        hosts1.vm.hostname = "hosts1"
        hosts1.vm.network 'private_network', ip: "192.168.1.20", virtualbox__intnet: "net1" # hosts1 - SRX1
        hosts1.ssh.insert_key = true
          hosts1.vm.provider :virtualbox do |vb|
            vb.memory = 512
            vb.gui = false
          end
        hosts1.vm.provision "shell", inline: <<-SHELL
        sudo ip route add 192.168.0.0/16 via 192.168.1.1 dev enp0s8
         SHELL
    end

# Jump Box 3
    config.vm.define "hosts3" do |hosts3|
        hosts3.vm.box = "ubuntu/xenial64"
        hosts3.vm.hostname = "hosts3"
        hosts3.vm.network 'private_network', ip: "192.168.4.20", virtualbox__intnet: "net5" # hosts3 - SRX1
        hosts3.ssh.insert_key = true
          hosts3.vm.provider :virtualbox do |vb|
            vb.memory = 512
            vb.gui = false
          end
        hosts3.vm.provision "shell", inline: <<-SHELL
        sudo ip route add 192.168.0.0/16 via 192.168.4.1 dev enp0s8
         SHELL
    end

# SRX 1 
  config.vm.define "srx1" do |srx1|
    srx1.vm.network "private_network", virtualbox__intnet: "net1" # SRX1 - hosts1
    srx1.vm.network "private_network", virtualbox__intnet: "net2" # SRX1 - SRX2
    srx1.vm.network "private_network", virtualbox__intnet: "net5" # SRX1 - hosts3
    srx1.vm.network "private_network", virtualbox__intnet: "net7" # SRX1 - SRX3    
    srx1.vm.box = "juniper/ffp-12.1X47-D15.4-packetmode"
      srx1.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--nicpromisc1", "allow-all", "--nicpromisc2", "allow-all", "--nicpromisc3", "allow-all", "--nicpromisc4", "allow-all"]
        vb.memory = 512
        vb.gui = false
      end
    srx1.vm.provision "junos_cli", path: 'config/srx1.cmd'
  end

# SRX 2
  config.vm.define "srx2" do |srx2|
    srx2.vm.network "private_network", virtualbox__intnet: "net2" # SRX2 - SRX1
    srx2.vm.network "private_network", virtualbox__intnet: "net3" # SRX2 - SRX3
    srx2.vm.network "private_network", virtualbox__intnet: "net8" # SRX2 - hosts5
    srx2.vm.box = "juniper/ffp-12.1X47-D15.4-packetmode"
      srx2.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--nicpromisc1", "allow-all", "--nicpromisc2", "allow-all", "--nicpromisc3", "allow-all", "--nicpromisc4", "allow-all"]
        vb.memory = 512
        vb.gui = false
      end
    srx2.vm.provision "junos_cli", path: 'config/srx2.cmd'
  end

# Jump Box 5
    config.vm.define "hosts5" do |hosts5|
        hosts5.vm.box = "ubuntu/xenial64"
        hosts5.vm.hostname = "hosts5"
        hosts5.vm.network 'private_network', ip: "192.168.5.20", virtualbox__intnet: "net8" # hosts2 - SRX3
        hosts5.ssh.insert_key = true
          hosts5.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--nicpromisc1", "allow-all",]
            vb.memory = 512
            vb.gui = false
          end
        hosts5.vm.provision "shell", inline: <<-SHELL
        sudo ip route add 192.168.0.0/16 via 192.168.5.1 dev enp0s8
         SHELL
    end


# SRX 3
  config.vm.define "srx3" do |srx3|
    srx3.vm.network "private_network", virtualbox__intnet: "net3" # SRX3 - SRX2
    srx3.vm.network "private_network", virtualbox__intnet: "net4" # SRX3 - hosts2
    srx3.vm.network "private_network", virtualbox__intnet: "net6" # SRX3 - hosts4
    srx3.vm.network "private_network", virtualbox__intnet: "net7" # SRX3 - SRX1
    srx3.vm.box = "juniper/ffp-12.1X47-D15.4-packetmode"
      srx3.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--nicpromisc1", "allow-all", "--nicpromisc2", "allow-all", "--nicpromisc3", "allow-all", "--nicpromisc4", "allow-all"]
        vb.memory = 512
        vb.gui = false
      end
    srx3.vm.provision "junos_cli", path: 'config/srx3.cmd'
  end

# Jump Box 2
    config.vm.define "hosts2" do |hosts2|
        hosts2.vm.box = "ubuntu/xenial64"
        hosts2.vm.hostname = "hosts2"
        hosts2.vm.network 'private_network', ip: "192.168.2.20", virtualbox__intnet: "net4" # hosts2 - SRX3
        hosts2.ssh.insert_key = true
          hosts2.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--nicpromisc1", "allow-all",]
            vb.memory = 512
            vb.gui = false
          end
        hosts2.vm.provision "shell", inline: <<-SHELL
        sudo ip route add 192.168.0.0/16 via 192.168.2.1 dev enp0s8
         SHELL
    end

# Jump Box 4
    config.vm.define "hosts4" do |hosts4|
        hosts4.vm.box = "ubuntu/xenial64"
        hosts4.vm.hostname = "hosts4"
        hosts4.vm.network 'private_network', ip: "192.168.3.20", virtualbox__intnet: "net6" # hosts4 - SRX1
        hosts4.ssh.insert_key = true
          hosts4.vm.provider :virtualbox do |vb|
            vb.memory = 512
            vb.gui = false
          end
        hosts4.vm.provision "shell", inline: <<-SHELL
        sudo ip route add 192.168.0.0/16 via 192.168.3.1 dev enp0s8
         SHELL
         end
  end
